package integrate

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateCMakeIntegration creates sea_packages/sea-cmake.cmake that consumers
// can include in their CMakeLists.txt to make all sea-installed packages
// discoverable via find_package().
//
// Usage in CMakeLists.txt:
//
//	include(sea_packages/sea-cmake.cmake)  # one line
//	find_package(cjson REQUIRED)           # just works
//	find_package(lz4 REQUIRED)             # just works
//
// This works because most CMake-built packages install config files to
// lib/cmake/{pkg}/. By adding each package's root to CMAKE_PREFIX_PATH,
// CMake's native find_package() finds them.
//
// For packages that don't ship CMake config files, we also generate
// basic Find{Pkg}.cmake modules.
func GenerateCMakeIntegration(seaPkgDir string) error {
	entries, err := os.ReadDir(seaPkgDir)
	if err != nil {
		return nil // no packages installed
	}

	var prefixPaths []string
	var needsFindModule []string

	for _, e := range entries {
		pkgPath := filepath.Join(seaPkgDir, e.Name())
		fi, err := os.Stat(pkgPath)
		if err != nil || !fi.IsDir() {
			continue
		}

		prefixPaths = append(prefixPaths, pkgPath)

		// Check if this package ships CMake config files
		cmakeDir := filepath.Join(pkgPath, "lib", "cmake")
		if _, err := os.Stat(cmakeDir); os.IsNotExist(err) {
			// No cmake config — we'll generate a basic FindModule
			needsFindModule = append(needsFindModule, e.Name())
		}
	}

	if len(prefixPaths) == 0 {
		return nil
	}

	sort.Strings(prefixPaths)
	sort.Strings(needsFindModule)

	var sb strings.Builder
	sb.WriteString("# Generated by sea — do not edit\n")
	sb.WriteString("# Include this file in your CMakeLists.txt:\n")
	sb.WriteString("#   include(sea_packages/sea-cmake.cmake)\n")
	sb.WriteString("#\n")
	sb.WriteString("# Then use find_package() as normal:\n")
	sb.WriteString("#   find_package(cjson REQUIRED)\n")
	sb.WriteString("#   target_link_libraries(myapp cjson::cjson)\n\n")

	// Set CMAKE_PREFIX_PATH so find_package works for packages with config files
	for _, p := range prefixPaths {
		sb.WriteString(fmt.Sprintf("list(APPEND CMAKE_PREFIX_PATH \"%s\")\n", p))
	}

	// Set CMAKE_MODULE_PATH for our generated Find modules
	if len(needsFindModule) > 0 {
		modulesDir := filepath.Join(seaPkgDir, ".cmake_modules")
		sb.WriteString(fmt.Sprintf("\nlist(APPEND CMAKE_MODULE_PATH \"%s\")\n", modulesDir))

		// Generate Find modules
		if err := os.MkdirAll(modulesDir, 0o755); err != nil {
			return err
		}
		for _, pkg := range needsFindModule {
			if err := generateFindModule(seaPkgDir, modulesDir, pkg); err != nil {
				continue // non-fatal
			}
		}
	}

	sb.WriteString("\n")

	cmakePath := filepath.Join(seaPkgDir, "sea-cmake.cmake")
	return os.WriteFile(cmakePath, []byte(sb.String()), 0o644)
}

// generateFindModule creates a basic Find{Pkg}.cmake for packages that don't
// ship their own CMake config files. This uses the standard CMake find_path
// and find_library pattern.
func generateFindModule(seaPkgDir, modulesDir, pkg string) error {
	pkgDir := filepath.Join(seaPkgDir, pkg)
	includeDir := filepath.Join(pkgDir, "include")
	libDir := filepath.Join(pkgDir, "lib")

	// Find a header to use as the detection hint
	headerHint := findFirstHeader(includeDir)

	// Find the library name
	libName := findPrimaryLib(libDir)

	// CMake module name uses the package name
	cmakeName := strings.ReplaceAll(pkg, "-", "_")
	upperName := strings.ToUpper(cmakeName)

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Generated by sea for package %q\n\n", pkg))

	if headerHint != "" {
		sb.WriteString(fmt.Sprintf("find_path(%s_INCLUDE_DIR\n", upperName))
		sb.WriteString(fmt.Sprintf("  NAMES %s\n", headerHint))
		sb.WriteString(fmt.Sprintf("  PATHS \"%s\"\n", includeDir))
		sb.WriteString("  NO_DEFAULT_PATH\n)\n\n")
	}

	if libName != "" {
		sb.WriteString(fmt.Sprintf("find_library(%s_LIBRARY\n", upperName))
		sb.WriteString(fmt.Sprintf("  NAMES %s\n", libName))
		sb.WriteString(fmt.Sprintf("  PATHS \"%s\"\n", libDir))
		sb.WriteString("  NO_DEFAULT_PATH\n)\n\n")
	}

	sb.WriteString("include(FindPackageHandleStandardArgs)\n")
	args := upperName + "_DEFAULT_MSG"
	if libName != "" {
		args += " " + upperName + "_LIBRARY"
	}
	if headerHint != "" {
		args += " " + upperName + "_INCLUDE_DIR"
	}
	sb.WriteString(fmt.Sprintf("find_package_handle_standard_args(%s %s)\n\n", cmakeName, args))

	// Create imported target
	sb.WriteString(fmt.Sprintf("if(%s_FOUND AND NOT TARGET %s::%s)\n", upperName, cmakeName, cmakeName))
	if libName != "" {
		sb.WriteString(fmt.Sprintf("  add_library(%s::%s UNKNOWN IMPORTED)\n", cmakeName, cmakeName))
		sb.WriteString(fmt.Sprintf("  set_target_properties(%s::%s PROPERTIES\n", cmakeName, cmakeName))
		sb.WriteString(fmt.Sprintf("    IMPORTED_LOCATION \"${%s_LIBRARY}\"\n", upperName))
		if headerHint != "" {
			sb.WriteString(fmt.Sprintf("    INTERFACE_INCLUDE_DIRECTORIES \"${%s_INCLUDE_DIR}\"\n", upperName))
		}
		sb.WriteString("  )\n")
	} else if headerHint != "" {
		// Header-only
		sb.WriteString(fmt.Sprintf("  add_library(%s::%s INTERFACE IMPORTED)\n", cmakeName, cmakeName))
		sb.WriteString(fmt.Sprintf("  set_target_properties(%s::%s PROPERTIES\n", cmakeName, cmakeName))
		sb.WriteString(fmt.Sprintf("    INTERFACE_INCLUDE_DIRECTORIES \"${%s_INCLUDE_DIR}\"\n", upperName))
		sb.WriteString("  )\n")
	}
	sb.WriteString("endif()\n")

	modulePath := filepath.Join(modulesDir, fmt.Sprintf("Find%s.cmake", cmakeName))
	return os.WriteFile(modulePath, []byte(sb.String()), 0o644)
}

// findFirstHeader returns the first .h or .hpp file path relative to the include dir.
func findFirstHeader(includeDir string) string {
	var result string
	filepath.Walk(includeDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		ext := filepath.Ext(info.Name())
		if ext == ".h" || ext == ".hpp" || ext == ".hxx" {
			rel, err := filepath.Rel(includeDir, path)
			if err == nil {
				result = rel
				return filepath.SkipAll
			}
		}
		return nil
	})
	return result
}

// findPrimaryLib returns the base library name (without lib prefix or extension)
// for the primary library in a lib directory.
func findPrimaryLib(libDir string) string {
	entries, err := os.ReadDir(libDir)
	if err != nil {
		return ""
	}
	for _, e := range entries {
		name := e.Name()
		// Prefer shared libraries
		if strings.HasPrefix(name, "lib") {
			if strings.HasSuffix(name, ".dylib") && !strings.Contains(name[3:len(name)-6], ".") {
				return name[3 : len(name)-6]
			}
			if strings.HasSuffix(name, ".so") {
				return name[3 : len(name)-3]
			}
		}
	}
	// Fall back to static
	for _, e := range entries {
		name := e.Name()
		if strings.HasPrefix(name, "lib") && strings.HasSuffix(name, ".a") {
			return name[3 : len(name)-2]
		}
	}
	return ""
}
