package integrate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRelocateCMakeConfigs(t *testing.T) {
	// Create a temporary package directory structure
	tmpDir, err := os.MkdirTemp("", "sea-relocate-test-*")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)

	cmakeDir := filepath.Join(tmpDir, "lib", "cmake", "libevent")
	if err := os.MkdirAll(cmakeDir, 0o755); err != nil {
		t.Fatal(err)
	}

	// Simulate a cmake config file with hardcoded absolute paths
	// (as produced by cmake --install on CI)
	installPrefix := tmpDir // simulate: the file was installed here
	cmakeContent := `# Generated by cmake
set(_IMPORT_PREFIX "` + installPrefix + `")
set_target_properties(libevent::core PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libevent_core-2.1.7.dylib"
  IMPORTED_SONAME_RELEASE "` + installPrefix + `/lib/libevent_core-2.1.7.dylib"
)
list(APPEND _cmake_import_check_files_for_libevent::core "${_IMPORT_PREFIX}/lib/libevent_core-2.1.7.dylib")
`

	cmakeFile := filepath.Join(cmakeDir, "LibeventTargets-release.cmake")
	if err := os.WriteFile(cmakeFile, []byte(cmakeContent), 0o644); err != nil {
		t.Fatal(err)
	}

	// Run relocation
	RelocateCMakeConfigs(tmpDir)

	// Read back and verify
	data, err := os.ReadFile(cmakeFile)
	if err != nil {
		t.Fatal(err)
	}
	result := string(data)

	// The absolute install prefix should be gone
	if strings.Contains(result, installPrefix) {
		t.Errorf("file still contains absolute path %q:\n%s", installPrefix, result)
	}

	// Should use ${CMAKE_CURRENT_LIST_DIR} relative paths
	if !strings.Contains(result, "${CMAKE_CURRENT_LIST_DIR}") {
		t.Errorf("file should contain ${CMAKE_CURRENT_LIST_DIR}:\n%s", result)
	}

	// IMPORTED_SONAME should also be relocated (this was the bug)
	if strings.Contains(result, "IMPORTED_SONAME_RELEASE \""+installPrefix) {
		t.Errorf("IMPORTED_SONAME still contains absolute path:\n%s", result)
	}

	t.Logf("Relocated content:\n%s", result)
}

func TestRelocateCMakeConfigs_ExternalPath(t *testing.T) {
	// Test case: SONAME contains a path from a DIFFERENT directory than
	// the install prefix (e.g., the build directory, not the install dir)
	tmpDir, err := os.MkdirTemp("", "sea-relocate-ext-*")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)

	cmakeDir := filepath.Join(tmpDir, "lib", "cmake", "foo")
	if err := os.MkdirAll(cmakeDir, 0o755); err != nil {
		t.Fatal(err)
	}

	// The install prefix is tmpDir, but SONAME points to a completely
	// different path (the original build machine)
	cmakeContent := `set_target_properties(foo::foo PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libfoo.dylib"
  IMPORTED_SONAME_RELEASE "/home/ci/build/output/lib/libfoo.1.2.3.dylib"
)
`
	cmakeFile := filepath.Join(cmakeDir, "fooTargets-release.cmake")
	if err := os.WriteFile(cmakeFile, []byte(cmakeContent), 0o644); err != nil {
		t.Fatal(err)
	}

	RelocateCMakeConfigs(tmpDir)

	data, err := os.ReadFile(cmakeFile)
	if err != nil {
		t.Fatal(err)
	}
	result := string(data)

	// The external path should be fixed to point to the package's lib/
	if strings.Contains(result, "/home/ci/build") {
		t.Errorf("file still contains external absolute path:\n%s", result)
	}

	t.Logf("Relocated content:\n%s", result)
}
